### ISSUE TITLE
Relative path off by one with baseUrl set

### ISSUE THREAD

**Issue by Soviut** [justkey007/tsc-alias#48] opened 2021-08-03 05:06 UTC
I had my tsconfig.json set up with

```json
  "baseUrl": "./src",
  "paths": {
      "@/*": [
        "./*"
      ]
    },
```

This compiled....

```javascript
import { PipelineStage } from `@/pipeline`
```

To the following (the relative path has an extra `../`)

```javascript
var pipeline_1 = require("../../../pipeline");
```

Changing the tsconfig to the following fixed the issue. Now the require only has `../../pipeline`.

```json
  "baseUrl": ".",
  "paths": {
      "@/*": [
        "./src/*"
      ]
    },
```

**Comment by justkey007** [comment] 2021-08-14 23:09
@Soviut 
I tried to reproduce your problem but couldn't. An example of a project to raise the problem encountered on your part will help us a lot. Thank you

Or tell me which file you made this import from?
> ```js
> import { PipelineStage } from `@/pipeline`
> ```

Check on [this](https://github.com/justkey007/tsc-alias/tree/justkey007/issue48/projects/project14) branch with project 14 if we have the same structure.

**Comment by Soviut** [comment] 2021-08-15 00:15
@justkey007 my project structure is

```
/myproject
  /src
    /pipeline
      index.ts
        (export { default as Pipeline } from './Pipeline')
        (export { default as PipelineStage } from './PipelineStage')
      Pipeline.ts
      PipelineStage.ts
      /parsers
        SomeParser.ts (import { PipelineStage } from '@/pipeline')
      /processors
        SomeProcessor.ts (import { PipelineStage } from '@/pipeline')

```

**Comment by justkey007** [comment] 2021-08-15 14:06
@Soviut 
I just [updated](https://github.com/justkey007/tsc-alias/tree/justkey007/issue48/projects/project14) the structure as you told me but I am not getting any issues. Maybe you had encountered the error with an old version if not try to provide me with a test project which raises your problem. Thank you

**Comment by Soviut** [comment] 2021-08-16 15:09
According to my package.json

```json
"tsc-alias": "^1.3.8",
```

Also my build script is

```json
"build": "tsc && tsc-alias"
```

**Comment by y-nk** [comment] 2021-08-17 04:26
I'm actually running into the exact same issue.

I've tried 2 ways:

1. 

```
  "baseUrl": "./",
  "paths": {
      "@/*": [
        "./src/*"
      ]
    },
  "outDir": "./dist",
```

which results in `tsc-alias` linking back to my src folder.

2.

```
  "baseUrl": "./src",
  "paths": {
      "@/*": [
        "./*"
      ]
    },
  "outDir": "./dist",
```

which results in `tsc-alias` linking back one time too much just like OP.

**Comment by justkey007** [comment] 2021-08-17 11:20
@Soviut @y-nk 
If you can add a test project that causes the tests to fail that would be super cool. Thank you

**Comment by nrayburn-tech** [comment] 2021-08-21 03:19
I am having a similar issue.  It can be worked around by specifying the `--dir` parameter.  For example, `npx tsc-alias --dir dist/src` in my case.

Initially, I did not need to specify the `--dir` parameter.  The issue presented when I imported a file from the same folder level as the `src` and `tsconfig` entries.  I think this is because the output of `tsc` changed from going directly into `dist` to going into `dist/src`.
A common thing to do for example is to import the `package.json` file from inside of the `src` folder, so you can get the version info from it.  I would expect this to present the problem.

Sorry, I don't have a full reproduction but hopefully this information helps some.

**Comment by AlanMorel** [comment] 2021-10-30 05:04
I can also confirm that I'm having the same general issue on 1.40. I get `compilerOptions.outDir is not set` on 1.4.0 but it is just fine when I revert back to 1.3.10.

**Comment by raouldeheer** [comment] 2021-10-30 06:53
@elclanrs @AlanMorel the issue of commander options being undefined has been fixed in pr #61. It will be fixed in the next release.

**Comment by AlanMorel** [comment] 2021-10-30 07:02
Very much appreciated, thank you! 🙏

**Comment by AlanMorel** [comment] 2021-11-09 01:39
Since this is a blocking issue for people, is there an estimate for when the release will be cut? Or can a smaller quicker release be made just to address this specific issue?

**Comment by raouldeheer** [comment] 2021-11-09 08:02
@justkey007 

> Since this is a blocking issue for people, is there an estimate for when the release will be cut? Or can a smaller quicker release be made just to address this specific issue?

Is there an estimate?

**Closed** 2021-11-15 13:31 UTC

**Comment by raouldeheer** [comment] 2021-11-15 13:34
@AlanMorel @elclanrs The 1.4.1 patch is now on npm. So the problem of "compilerOptions.outDir is not set" should be fixed.
Does the fix by @nrayburn-tech work for everyone?

**Comment by AlanMorel** [comment] 2021-11-16 00:21
1.4.1's looking good on my end!
